# Use root/root as user/password credentials
version: '3.1'

services:

  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PRODUCER
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "13306:3306"
    networks:
      - spring-cloud-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    environment:
      - RABBITMQ_ERLANG_COOKIE=secret cookie here
    ports:
      - "15672:5672"

    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - spring-cloud-network

  producer:
    container_name: producer
    build: ./producer/
    image: producer:latest
    restart: always
    depends_on:
      - db
      - rabbitmq
    links:
      - db
      - rabbitmq
    networks:
      - spring-cloud-network

  broker:
    container_name: broker
    build: ./broker/
    image: broker:latest
    restart: always
    depends_on:
      - db
      - rabbitmq
    links:
      - db
      - rabbitmq
    networks:
      - spring-cloud-network

  consumer:
    container_name: consumer
    build: ./consumer/
    image: consumer:latest
    restart: always
    depends_on:
      - db
      - rabbitmq
    links:
      - db
      - rabbitmq
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge